name: Deploy on Github Pages

on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2.4.0
    
    - name: Setup .Net Core Project
      uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: 6.0.101
        
    - name: Publish .Net Core Project
      run: dotnet publish -c Release -o release --nologo
      
    - name: Change base-tag in index.html rfom / to BlazorAppWasm
      run: sed -i 's/<base href="\/" \/<base href="\/BlazorAppWasm\/" \/>g' release/wwwroot/index.html
      
    - name: copy index to 404
      run: cp release/wwwroot/index.html release/wwwroot/404.html
      
    - name: add .noxekyll ile
      run: touch release/wwwroot/.nojekyll
      
    - name: Commit wwwroot to gh pages
      uses: JamesIves/github-pages-deploy-action@4.2.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        older: release/wwwroot
